"""Add missing user fields

Revision ID: 398d71644beb
Revises: 9cf2b9a75342
Create Date: 2025-10-31 07:01:59.893671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398d71644beb'
down_revision = '9cf2b9a75342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wishlist_id', sa.UUID(), nullable=False),
    sa.Column('artwork_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artwork_id'], ['artworks.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_public_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_available', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carrier', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('shipping_country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('shipping_postal_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('transaction_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('shipping_postal_code')
        batch_op.drop_column('shipping_country')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('shipping_address')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('estimated_delivery')
        batch_op.drop_column('carrier')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('artworks', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_available')
        batch_op.drop_column('image_public_id')

    op.drop_table('wishlist_items')
    op.drop_table('wishlists')
    # ### end Alembic commands ###
